### ISSUE TITLE
error of train

### ISSUE THREAD

**Issue by ThoamsDong** [thuml/Universal-Domain-Adaptation#1]
Thanks for your impressive work! When I run your code in my workstation, it always reports "[easydl] tensorflow not available!"  And I satisfy the requirements which you mentioned in "readme". What should I do?
![1](https://user-images.githubusercontent.com/34698969/56204011-0b652c80-6079-11e9-80b5-9f42a0ce4b63.PNG)

**Comment by youkaichao** [comment]
`it always reports "[easydl] tensorflow not available!"`

Maybe you have not installed tensorflow.

And the exception is about the `tensorboardX `, you should also install the `tensorboard`.

To sum up, install `tensorflow` && `tensorboard`.

**Comment by youkaichao** [comment]
@ThoamsDong  please check 75a8e5d8bbdca21e03503a19714c8e230db569dd, it should work without `tensorflow` now.

**Comment by eehjc** [comment]
Hello, when I run this code, it reports 
File "/home/huangjc/uda/main.py", line 27 log_dir = f'{args.log.root_dir}/{now}'
                                         ^
SyntaxError: invalid syntax, in our yaml file, log is set as : root_dir: /home/huangjc/uda/time.

**Comment by youkaichao** [comment]
@eehjc  Please check the requirements, `python3` is required. Maybe you are using `python2`. The `f-string` syntax is introduced in `python3.6`. 

![image](https://user-images.githubusercontent.com/23236638/56873864-fff60600-6a67-11e9-9034-bdd5e915b631.png)

**Comment by eehjc** [comment]
We check the requirements, and the version of python is 3.5,  and pytorch is 1.0, but it still reports
File "/home/huangjc/uda/main.py", line 27 log_dir = f'{args.log.root_dir}/{now}'
^
SyntaxError: invalid syntax, in our yaml file, log is set as : root_dir: /home/huangjc/uda/time. I want to know if we make mistake to the setting of root_dir?

**Comment by eehjc** [comment]
only python 3.6 can support the f"{}", thanks for your reply

**Comment by youkaichao** [comment]
To make things clear, I have updated the `requirements` in `README`.

**Comment by Dayro-9** [comment]
Hello, I run the code on Google Colab and met the similar error ' I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
[easydl] tensorflow not available!'
Have you solved the error? if yes, could you please help me to solve the above error?
