### ISSUE TITLE
在运行python main.py --config officehome-train-config.yaml中遇到的问题

### ISSUE THREAD

**Issue by Dayro-9** [thuml/Universal-Domain-Adaptation#10]
您好，最近拜读Universal Domain Adaptation，对UAN算法非常感兴趣，谢谢你们分享代码！在调试代码的过程中，我遇到了几个问题，想请教一下：
1.pretrained_model可以采用离线下载的pytorch预训练模型吗？例如，通过‘https://download.pytorch.org/models/resnet50-19c8e357.pth’下载ResNet-50的预训练模型进行实验
2.在Google Colab上运行“！python main.py --config office-train-config.yaml”时，遇到了图中的报错信息，该如何解决？
<img width="547" alt="ab637c18669d538f4d78b51f4b45000" src="https://user-images.githubusercontent.com/59091691/95834646-ce621f00-0d6f-11eb-9d4d-4f91a995d0cb.png">
感谢你的阅读，期待回复！

**Comment by zhouzhou9999** [comment]
您好，我遇到了跟你一样的问题。能否说下@Dayro-9

**Comment by Dayro-9** [comment]
@zhouzhou9999 
1）关于预训练模型，作者用的就是pytorch自带的预训练模型(https://github.com/thuml/Universal-Domain-Adaptation/blob/5d7caa95af7e3675305c542253c4e372801897d2/net.py#L32) 
这里的pretrained_model的路径应该不是必填的，我试过不设置路径，程序会自动从pytorch官网下载resnet50的模型
(https://github.com/thuml/Universal-Domain-Adaptation/blob/5d7caa95af7e3675305c542253c4e372801897d2/office-train-config.yaml#L18)
2）关于easydl库，可以参见这个回答(https://github.com/thuml/easydl/issues/1)
不影响程序运作

**Comment by Dayro-9** [comment]
@zhouzhou9999 请问你最后复现出office-31的时候，测试结果和论文差不多吗？
