### ISSUE TITLE
the coefficient scheduler for gradient reversal module

### ISSUE THREAD

**Issue by cmhungsteve** [thuml/Universal-Domain-Adaptation#2]
`self.grl = GradientReverseModule(lambda step: aToBSheduler(step, 0.0, 1.0, gamma=10, max_iter=10000))`

It seems that `max_iter` is set as 10000.

From the DANN paper, I thought it depends on the total iteration number during training.
Is there any reason to use a fixed number?

Thank you.

**Comment by youkaichao** [comment]
Because the total iterations in our experiments are basically the same.
