### ISSUE TITLE
About reproduce the result of OfficeHome 

### ISSUE THREAD

**Issue by Solacex** [thuml/Universal-Domain-Adaptation#6]
![image](https://user-images.githubusercontent.com/12868455/76139969-c3dcfa00-60a9-11ea-92ce-7e2f61d069f9.png)

Hello,  I could not find the 'Art.txt'  from the downloaded OfficeHome, How to get it ?

Thanks~

**Comment by Openning07** [comment]
In the **OfficeHome** data you download ...

**Comment by Solacex** [comment]
> In the **OfficeHome** data you download ...

I cannot find the file in the OfficeHome I download (http://hemanthdv.org/OfficeHome-Dataset/)

**Comment by justlovebarbecue** [comment]
Hi @Solacex , I meet the same error, have you fixed it?
Thanks.

**Comment by Solacex** [comment]
> Hi @Solacex , I meet the same error, have you fixed it?
> Thanks.

Yes, I generate the txt files by myself.

**Comment by justlovebarbecue** [comment]
ohh, got u. Thx, I'll try that. @Solacex

**Comment by greeneggsandyaml** [comment]
If you have generated the files, would it be possible for you to share a copy of them? It would greatly help others who are trying to reproduce this repo's results!

**Comment by sparshgarg23** [comment]
@greeneggsandyaml  you might want to take a look at this
https://github.com/CDTrans/CDTrans/tree/master/data/OfficeHomeDataset
Also,@solacex please confirm if the art.txt in CDTrans is similar to the one that you generated?If possible kindly share the method you used to generate them.
